export interface ThemesModel {
    navColor: string,
    bgColor: string,
    color: string,
    borderButton: string,
    borderRadiusButton: string,
    hoverTextColor: string,
    hoverBgColor: string,
    borderColor: string,
    heightLabel: string,
    smallColor: string,
    noteColor: string,
    color1?: string,
    color2?: string,
    color3?: string,
    bgColor1?: string,
    mainColor: string,
    textColor: string,
    borderColor2: string,
}